#+AUTHOR: esac <esac-io@tutanota.com>
#+PROPERTY: header-args :tangle no

* Introduction

  Just a simple Emacs theme with focus on transparent frames.
  The name is just a humble homage to a grate artist called: Jean
  "moebius" Giraud, may you rest in peace and love.

  And a big =thank you= for your work and contributions, they are
  so inspiring.

* Overview

  If you use some composition software it's possible to make Emacs
  window (the frame) transparent over the display server (Xorg for
  example), a lot of themes does not take that in count when the
  colors are choose to compose the theme in question.

  As I use Emacs with compton compositor to make the frame transparent
  (about 90% opacity is applied) was necessary to create a new theme to
  assert the faces (colors and other properties), to provide,
  a clear view of the items displayed on the screen.

  The files moebius-theme.el (the dark version) and
  moebius-theme-yellow.el (light yellow version) are the results
  of this experimentation over the last ear.

* Installation

  As usual just clone the repository and put them (the lisp theme
  files) where =custom-theme-load-path= variable are point to
  (probably =~/.emacs.d/themes=), do enable then dynamically use
  the command: =M-x load-theme RET= and select the =moebius= theme.

  To persist that between Emacs sessions put the snippet of code below
  somewhere inside in your ~init.el~ file.

  #+BEGIN_SRC emacs-lisp

  ;; add eos-theme-dir to theme load path
  (add-to-list 'custom-theme-load-path
               (concat user-emacs-directory "themes"))

  ;; load theme
  (load-theme 'moebius-yellow t)

  #+END_SRC

* References

  1. https://www.gnu.org/software/emacs/manual/html_node/elisp/Custom-Themes.html
  2. https://gitlab.com/protesilaos/modus-themes
  3. https://github.com/bbatsov/zenburn-emacs

* LICENSE
  MIT

* EOF
  An artist must smash down the systems that domesticate the mind.
  | Jean Giraud |
